### PR TITLE
Rails 5

### PR DESCRIPTION
**Pull request by n-rodriguez**

### CODE REVIEW

**Comment by n-rodriguez** [comment]
Ping!

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by januszm** [comment]
@n-rodriguez I couldn't work on this more, I'm swamped with current projects.

Did you have a chance to test these changes in a working Rails 5 app ? It's extremely difficult for me to do extensive testing at the moment so I'll trust your judgement here. LMK and I'll merge this change since it looks good.

**Comment by n-rodriguez** [comment]
> Did you have a chance to test these changes in a working Rails 5 app ?

Yes and it works :)

There is a slight change here : https://github.com/januszm/store_base_sti_class/pull/1/commits/c8f63ce0be80f36bb9e1cb3a03ae60e09b82c593#diff-fe9a4a7d3c19be91e5fcc5f6987a642fR35 and here : https://github.com/januszm/store_base_sti_class/pull/1/commits/c8f63ce0be80f36bb9e1cb3a03ae60e09b82c593#diff-5f0a22c398ea7dcdfbdfab19368ad0ebR128 but it works.

**Comment by januszm** [comment]
Thank you sir!

**Pull request merged**
